site_name: PySpark Data Source Formats
site_description: This project provides a collection of custom data source formats for Apache Spark 4.0+ and Databricks.
site_url: https://pysparkformat.readthedocs.io/en/latest/
