name: Python package

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pyspark==4.0.0.dev2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run ruff
        run: |
          ruff check --output-format=github .
      - name: Test with pytest
        run: |
          cd src && pytest ../tests/
