on:
  push:
    tags:
      - 'release/v*'

name: Release

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pyspark==4.0.0.dev2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run ruff
        run: |
          ruff check --output-format=github .
      - name: Test with pytest
        run: |
          cd src && pytest ../tests/
      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
